# Generated by Django 4.1.3 on 2022-11-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_owner', models.CharField(max_length=300)),
                ('sponser', models.CharField(max_length=300)),
                ('autherity', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
